### ISSUE TITLE
Tabs that look like tabs

### ISSUE THREAD

**Issue by Madis0** [DarkKronicle/AdvancedChat#10]
The current tab system is a single wide button, which means if you have more than 3 tabs, it will be a lot to click.

**Comment by DarkKronicle** [comment]
I am new to making buttons and gui's for mods and I just wanted to get the mod released. This is in the plans for future releases. I'm thinking like a couple different options for how the tab button would function.

**Comment by DarkKronicle** [comment]
Reworked some stuff, not entirely happy with it yet, may not be as good as some other mods, but I think it functions really nicely. It has a nice clean look with the function behind it. I'll probably come back to this later at some point. I'm going to close this issue because it now is a lot better then it was before.

Should be available in version 2.0.3 soon!
![image](https://user-images.githubusercontent.com/38167691/88247174-074f9380-cc5a-11ea-9eff-490a2097e3b0.png)

**Comment by Madis0** [comment]
How about making those tabs horizontal and moving them to where the big button currently is? Would look more like a browser and allow bigger tab titles too. The current tab could be opaque (black).

**Comment by DarkKronicle** [comment]
I'll keep trying to improve it. Right now I'm trying to write an API that helps making nice clean ui's.
