### ISSUE TITLE
[FEATURE] 24h format for chat, log and tab

### ISSUE THREAD

**Issue by sphings79** [DarkKronicle/AdvancedChat#20]
Hi,

would be great to have an option to switch between 12/24h format.
Also on 1.15.2
sorry for so much requests ...

regards

sphings

**Comment by DarkKronicle** [comment]
This is already a feature. It uses _DateTimeFormatter_ to format what time it is. https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
Anything in the section ***Patterns for Formatting and Parsing*** (Scroll down a bit) is supported. So if you want it to be 24 hour format, you would put in TimeFormat `kk` instead of `hh`
