### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by sphings79** [DarkKronicle/AdvancedChat#6]
Hi,

I'm using advancedchat-0.1.1.jar for 1.15.2 and it seems not to be possible to filter out private messages.
If i use the filter with "--> Du]" it won't get filtered.
I've also just tried "Du]", it also wont work.

regards

sphings

**Comment by DarkKronicle** [comment]
There is some weird behavior with minecraft text and the way that I am filtering in 1.15. Are there different colors in the message? Because minecraft uses a hidden symbol to change colors.

So in minecraft it could look like `Du]` with a color change in the middle. What actually happens is something like this: `Du§7]`. In 1.16 this doesn't happen, but I'll see if I can get it working in 1.15.

**Comment by DarkKronicle** [comment]
If you want to update to v2 for 1.15 I just released it on the CurseForge page. I'll be mainly supporting 1.16, but I'll try to backport some features.
