### ISSUE TITLE
[FEATURE] Chat calculator

### ISSUE THREAD

**Issue by K0-RR** [DarkKronicle/AdvancedChat#60]
I would like something like this
https://www.curseforge.com/minecraft/mc-mods/chatcalc

@Ozaxx thanks for this idea.

**Comment by DarkKronicle** [comment]
Finished step 1 of HUD rewrite. Am working on chat processors then will probably come to this.

**Comment by K0-RR** [comment]
What about making it work like the equations in Excel, instead of clicking the tab button? (You would need to type "=" to make it interpret the text as an equation).

**Comment by DarkKronicle** [comment]
Currently I'm thinking about having you delegate an equation you want with `[]`'s. It will then parse it and then if you click enter it will replace it. Something like:

(Chat Box): 
I need [64 * 3] stone bricks.

If you hit return (lilke it's a command) it will replace to
I need 192 stone bricks.

**Comment by DarkKronicle** [comment]
Either that or I could maybe find some library to automagically parse equations...

**Comment by DarkKronicle** [comment]
![image](https://user-images.githubusercontent.com/38167691/113805927-a7811600-971e-11eb-8e85-3073dfb5709f.png)
Got custom suggestions to work. Still a bit buggy, but hopefully chat calc soon?

**Comment by HappyClownn** [comment]
It's nice to see you struggling so hard with the mod you made.. I can't wait for the updates you bring!

**Comment by DarkKronicle** [comment]
I got it to work :) 

![](https://media.discordapp.net/attachments/753693459369427047/829435245375389796/unknown.png)

![](https://media.discordapp.net/attachments/753693459369427047/829435167944081438/unknown.png)

I'm not going to publish this release *just* yet to curse because I still need to add configuration for a lot of stuff. Though if you do want to try it, you can find it on my [Discord](https://discord.gg/WnaE3uZxDA)
