### ISSUE TITLE
[FEATURE] Add ability to disable mod highlighting/autocomplete

### ISSUE THREAD

**Issue by bbfh-dev** [DarkKronicle/AdvancedChat#94]
I work with datapacks, and honestly, I usually develop them without AdvancedChat mod because I can't find an option to completely disable custom chat formatting. And it's being annoying sometimes.

When I type a command, the colors, the highlighting and the suggestions are different, I don't want it. I would like to be able to disable custom chat highlighting somewhere (if disable everything possible in settings, it doesn't help).

**This mod is a master piece and I would like if it would have slash commands formatting optional!**

**Comment by x86-39** [comment]
I have noticed AdvancedChat changes the order of tab completion entries, so this is probably related. I have to disable it when creating plugins because I can't tell if something is at fault on my end or not. If it's possible with the existing code base I would like a way to revert it to the vanilla one, however if not I could do some testing to see in what scenarios it changes it, and try to find the cause.

**Comment by DarkKronicle** [comment]
The current plan for AdvancedChat is to split it up into separate mods and modules. On the discord there has been some discussion. Highlighting and auto-complete will branch off into a different module that will be easy to add or remove it.

**Comment by DarkKronicle** [comment]
When I split it up I'll take a look into some of these issues.

**Comment by DarkKronicle** [comment]
This is now added in the beta! If you come across problems with the formatting and suggestions I would really appreciated it if you add it to the new [issue tracker](https://github.com/DarkKronicle/AdvancedChatBox/issues)
